### ISSUE TITLE
Using more bootstrap pagination classes

### ISSUE THREAD

**Issue by bhanuone** [bootstrap-ruby/will_paginate-bootstrap#37]
Hi, i want to use other bootstarp pagination classes "pagination-lg" and "pagination-sm" rather than the default one. How can i do that?

**Comment by zerodayz** [comment]
To change the size just append
```css
.pagination {
        font-size: 11px;
}
```
to app/assets/stylesheets/custom.css.scss
